//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1Tests.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://www.gzsums.net/crisisValue/")]
    [System.SerializableAttribute()]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1Tests.ServiceReference1.RequestHeader requestHeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string requestBodyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WebApplication1Tests.ServiceReference1.RequestHeader requestHeader {
            get {
                return this.requestHeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.requestHeaderField, value) != true)) {
                    this.requestHeaderField = value;
                    this.RaisePropertyChanged("requestHeader");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string requestBody {
            get {
                return this.requestBodyField;
            }
            set {
                if ((object.ReferenceEquals(this.requestBodyField, value) != true)) {
                    this.requestBodyField = value;
                    this.RaisePropertyChanged("requestBody");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestHeader", Namespace="http://www.gzsums.net/crisisValue/")]
    [System.SerializableAttribute()]
    public partial class RequestHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string senderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string requestTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgPriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgVersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sender {
            get {
                return this.senderField;
            }
            set {
                if ((object.ReferenceEquals(this.senderField, value) != true)) {
                    this.senderField = value;
                    this.RaisePropertyChanged("sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string receiver {
            get {
                return this.receiverField;
            }
            set {
                if ((object.ReferenceEquals(this.receiverField, value) != true)) {
                    this.receiverField = value;
                    this.RaisePropertyChanged("receiver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string requestTime {
            get {
                return this.requestTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.requestTimeField, value) != true)) {
                    this.requestTimeField = value;
                    this.RaisePropertyChanged("requestTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msgType {
            get {
                return this.msgTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.msgTypeField, value) != true)) {
                    this.msgTypeField = value;
                    this.RaisePropertyChanged("msgType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string msgId {
            get {
                return this.msgIdField;
            }
            set {
                if ((object.ReferenceEquals(this.msgIdField, value) != true)) {
                    this.msgIdField = value;
                    this.RaisePropertyChanged("msgId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string msgPriority {
            get {
                return this.msgPriorityField;
            }
            set {
                if ((object.ReferenceEquals(this.msgPriorityField, value) != true)) {
                    this.msgPriorityField = value;
                    this.RaisePropertyChanged("msgPriority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string msgVersion {
            get {
                return this.msgVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.msgVersionField, value) != true)) {
                    this.msgVersionField = value;
                    this.RaisePropertyChanged("msgVersion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://www.gzsums.net/crisisValue/")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1Tests.ServiceReference1.ResponseHeader responseHeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responseBodyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WebApplication1Tests.ServiceReference1.ResponseHeader responseHeader {
            get {
                return this.responseHeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.responseHeaderField, value) != true)) {
                    this.responseHeaderField = value;
                    this.RaisePropertyChanged("responseHeader");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string responseBody {
            get {
                return this.responseBodyField;
            }
            set {
                if ((object.ReferenceEquals(this.responseBodyField, value) != true)) {
                    this.responseBodyField = value;
                    this.RaisePropertyChanged("responseBody");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseHeader", Namespace="http://www.gzsums.net/crisisValue/")]
    [System.SerializableAttribute()]
    public partial class ResponseHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string senderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string requestTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgPriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sender {
            get {
                return this.senderField;
            }
            set {
                if ((object.ReferenceEquals(this.senderField, value) != true)) {
                    this.senderField = value;
                    this.RaisePropertyChanged("sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string receiver {
            get {
                return this.receiverField;
            }
            set {
                if ((object.ReferenceEquals(this.receiverField, value) != true)) {
                    this.receiverField = value;
                    this.RaisePropertyChanged("receiver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string requestTime {
            get {
                return this.requestTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.requestTimeField, value) != true)) {
                    this.requestTimeField = value;
                    this.RaisePropertyChanged("requestTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msgType {
            get {
                return this.msgTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.msgTypeField, value) != true)) {
                    this.msgTypeField = value;
                    this.RaisePropertyChanged("msgType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string msgId {
            get {
                return this.msgIdField;
            }
            set {
                if ((object.ReferenceEquals(this.msgIdField, value) != true)) {
                    this.msgIdField = value;
                    this.RaisePropertyChanged("msgId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string msgPriority {
            get {
                return this.msgPriorityField;
            }
            set {
                if ((object.ReferenceEquals(this.msgPriorityField, value) != true)) {
                    this.msgPriorityField = value;
                    this.RaisePropertyChanged("msgPriority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string msgVersion {
            get {
                return this.msgVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.msgVersionField, value) != true)) {
                    this.msgVersionField = value;
                    this.RaisePropertyChanged("msgVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ErrCode {
            get {
                return this.ErrCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrCodeField, value) != true)) {
                    this.ErrCodeField = value;
                    this.RaisePropertyChanged("ErrCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ErrMessage {
            get {
                return this.ErrMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrMessageField, value) != true)) {
                    this.ErrMessageField = value;
                    this.RaisePropertyChanged("ErrMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebApplication1Tests.ServiceReference1.HelloWorldResponse HelloWorld(WebApplication1Tests.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1Tests.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WebApplication1Tests.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name req from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrisisAdd", ReplyAction="*")]
        WebApplication1Tests.ServiceReference1.CrisisAddResponse CrisisAdd(WebApplication1Tests.ServiceReference1.CrisisAddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrisisAdd", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1Tests.ServiceReference1.CrisisAddResponse> CrisisAddAsync(WebApplication1Tests.ServiceReference1.CrisisAddRequest request);
        
        // CODEGEN: Generating message contract since element name req from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrisisUpdate", ReplyAction="*")]
        WebApplication1Tests.ServiceReference1.CrisisUpdateResponse CrisisUpdate(WebApplication1Tests.ServiceReference1.CrisisUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrisisUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1Tests.ServiceReference1.CrisisUpdateResponse> CrisisUpdateAsync(WebApplication1Tests.ServiceReference1.CrisisUpdateRequest request);
        
        // CODEGEN: Generating message contract since element name req from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrisisStatusFeedback", ReplyAction="*")]
        WebApplication1Tests.ServiceReference1.CrisisStatusFeedbackResponse CrisisStatusFeedback(WebApplication1Tests.ServiceReference1.CrisisStatusFeedbackRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrisisStatusFeedback", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1Tests.ServiceReference1.CrisisStatusFeedbackResponse> CrisisStatusFeedbackAsync(WebApplication1Tests.ServiceReference1.CrisisStatusFeedbackRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1Tests.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebApplication1Tests.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1Tests.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebApplication1Tests.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrisisAddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrisisAdd", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1Tests.ServiceReference1.CrisisAddRequestBody Body;
        
        public CrisisAddRequest() {
        }
        
        public CrisisAddRequest(WebApplication1Tests.ServiceReference1.CrisisAddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrisisAddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication1Tests.ServiceReference1.Request req;
        
        public CrisisAddRequestBody() {
        }
        
        public CrisisAddRequestBody(WebApplication1Tests.ServiceReference1.Request req) {
            this.req = req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrisisAddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrisisAddResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1Tests.ServiceReference1.CrisisAddResponseBody Body;
        
        public CrisisAddResponse() {
        }
        
        public CrisisAddResponse(WebApplication1Tests.ServiceReference1.CrisisAddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrisisAddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication1Tests.ServiceReference1.Response CrisisAddResult;
        
        public CrisisAddResponseBody() {
        }
        
        public CrisisAddResponseBody(WebApplication1Tests.ServiceReference1.Response CrisisAddResult) {
            this.CrisisAddResult = CrisisAddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrisisUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrisisUpdate", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1Tests.ServiceReference1.CrisisUpdateRequestBody Body;
        
        public CrisisUpdateRequest() {
        }
        
        public CrisisUpdateRequest(WebApplication1Tests.ServiceReference1.CrisisUpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrisisUpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication1Tests.ServiceReference1.Request req;
        
        public CrisisUpdateRequestBody() {
        }
        
        public CrisisUpdateRequestBody(WebApplication1Tests.ServiceReference1.Request req) {
            this.req = req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrisisUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrisisUpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1Tests.ServiceReference1.CrisisUpdateResponseBody Body;
        
        public CrisisUpdateResponse() {
        }
        
        public CrisisUpdateResponse(WebApplication1Tests.ServiceReference1.CrisisUpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrisisUpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication1Tests.ServiceReference1.Response CrisisUpdateResult;
        
        public CrisisUpdateResponseBody() {
        }
        
        public CrisisUpdateResponseBody(WebApplication1Tests.ServiceReference1.Response CrisisUpdateResult) {
            this.CrisisUpdateResult = CrisisUpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrisisStatusFeedbackRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrisisStatusFeedback", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1Tests.ServiceReference1.CrisisStatusFeedbackRequestBody Body;
        
        public CrisisStatusFeedbackRequest() {
        }
        
        public CrisisStatusFeedbackRequest(WebApplication1Tests.ServiceReference1.CrisisStatusFeedbackRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrisisStatusFeedbackRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication1Tests.ServiceReference1.Request req;
        
        public CrisisStatusFeedbackRequestBody() {
        }
        
        public CrisisStatusFeedbackRequestBody(WebApplication1Tests.ServiceReference1.Request req) {
            this.req = req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrisisStatusFeedbackResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrisisStatusFeedbackResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1Tests.ServiceReference1.CrisisStatusFeedbackResponseBody Body;
        
        public CrisisStatusFeedbackResponse() {
        }
        
        public CrisisStatusFeedbackResponse(WebApplication1Tests.ServiceReference1.CrisisStatusFeedbackResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrisisStatusFeedbackResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication1Tests.ServiceReference1.Response CrisisStatusFeedbackResult;
        
        public CrisisStatusFeedbackResponseBody() {
        }
        
        public CrisisStatusFeedbackResponseBody(WebApplication1Tests.ServiceReference1.Response CrisisStatusFeedbackResult) {
            this.CrisisStatusFeedbackResult = CrisisStatusFeedbackResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebApplication1Tests.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebApplication1Tests.ServiceReference1.WebService1Soap>, WebApplication1Tests.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1Tests.ServiceReference1.HelloWorldResponse WebApplication1Tests.ServiceReference1.WebService1Soap.HelloWorld(WebApplication1Tests.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebApplication1Tests.ServiceReference1.HelloWorldRequest inValue = new WebApplication1Tests.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebApplication1Tests.ServiceReference1.HelloWorldRequestBody();
            WebApplication1Tests.ServiceReference1.HelloWorldResponse retVal = ((WebApplication1Tests.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1Tests.ServiceReference1.HelloWorldResponse> WebApplication1Tests.ServiceReference1.WebService1Soap.HelloWorldAsync(WebApplication1Tests.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1Tests.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WebApplication1Tests.ServiceReference1.HelloWorldRequest inValue = new WebApplication1Tests.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebApplication1Tests.ServiceReference1.HelloWorldRequestBody();
            return ((WebApplication1Tests.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1Tests.ServiceReference1.CrisisAddResponse WebApplication1Tests.ServiceReference1.WebService1Soap.CrisisAdd(WebApplication1Tests.ServiceReference1.CrisisAddRequest request) {
            return base.Channel.CrisisAdd(request);
        }
        
        public WebApplication1Tests.ServiceReference1.Response CrisisAdd(WebApplication1Tests.ServiceReference1.Request req) {
            WebApplication1Tests.ServiceReference1.CrisisAddRequest inValue = new WebApplication1Tests.ServiceReference1.CrisisAddRequest();
            inValue.Body = new WebApplication1Tests.ServiceReference1.CrisisAddRequestBody();
            inValue.Body.req = req;
            WebApplication1Tests.ServiceReference1.CrisisAddResponse retVal = ((WebApplication1Tests.ServiceReference1.WebService1Soap)(this)).CrisisAdd(inValue);
            return retVal.Body.CrisisAddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1Tests.ServiceReference1.CrisisAddResponse> WebApplication1Tests.ServiceReference1.WebService1Soap.CrisisAddAsync(WebApplication1Tests.ServiceReference1.CrisisAddRequest request) {
            return base.Channel.CrisisAddAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1Tests.ServiceReference1.CrisisAddResponse> CrisisAddAsync(WebApplication1Tests.ServiceReference1.Request req) {
            WebApplication1Tests.ServiceReference1.CrisisAddRequest inValue = new WebApplication1Tests.ServiceReference1.CrisisAddRequest();
            inValue.Body = new WebApplication1Tests.ServiceReference1.CrisisAddRequestBody();
            inValue.Body.req = req;
            return ((WebApplication1Tests.ServiceReference1.WebService1Soap)(this)).CrisisAddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1Tests.ServiceReference1.CrisisUpdateResponse WebApplication1Tests.ServiceReference1.WebService1Soap.CrisisUpdate(WebApplication1Tests.ServiceReference1.CrisisUpdateRequest request) {
            return base.Channel.CrisisUpdate(request);
        }
        
        public WebApplication1Tests.ServiceReference1.Response CrisisUpdate(WebApplication1Tests.ServiceReference1.Request req) {
            WebApplication1Tests.ServiceReference1.CrisisUpdateRequest inValue = new WebApplication1Tests.ServiceReference1.CrisisUpdateRequest();
            inValue.Body = new WebApplication1Tests.ServiceReference1.CrisisUpdateRequestBody();
            inValue.Body.req = req;
            WebApplication1Tests.ServiceReference1.CrisisUpdateResponse retVal = ((WebApplication1Tests.ServiceReference1.WebService1Soap)(this)).CrisisUpdate(inValue);
            return retVal.Body.CrisisUpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1Tests.ServiceReference1.CrisisUpdateResponse> WebApplication1Tests.ServiceReference1.WebService1Soap.CrisisUpdateAsync(WebApplication1Tests.ServiceReference1.CrisisUpdateRequest request) {
            return base.Channel.CrisisUpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1Tests.ServiceReference1.CrisisUpdateResponse> CrisisUpdateAsync(WebApplication1Tests.ServiceReference1.Request req) {
            WebApplication1Tests.ServiceReference1.CrisisUpdateRequest inValue = new WebApplication1Tests.ServiceReference1.CrisisUpdateRequest();
            inValue.Body = new WebApplication1Tests.ServiceReference1.CrisisUpdateRequestBody();
            inValue.Body.req = req;
            return ((WebApplication1Tests.ServiceReference1.WebService1Soap)(this)).CrisisUpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1Tests.ServiceReference1.CrisisStatusFeedbackResponse WebApplication1Tests.ServiceReference1.WebService1Soap.CrisisStatusFeedback(WebApplication1Tests.ServiceReference1.CrisisStatusFeedbackRequest request) {
            return base.Channel.CrisisStatusFeedback(request);
        }
        
        public WebApplication1Tests.ServiceReference1.Response CrisisStatusFeedback(WebApplication1Tests.ServiceReference1.Request req) {
            WebApplication1Tests.ServiceReference1.CrisisStatusFeedbackRequest inValue = new WebApplication1Tests.ServiceReference1.CrisisStatusFeedbackRequest();
            inValue.Body = new WebApplication1Tests.ServiceReference1.CrisisStatusFeedbackRequestBody();
            inValue.Body.req = req;
            WebApplication1Tests.ServiceReference1.CrisisStatusFeedbackResponse retVal = ((WebApplication1Tests.ServiceReference1.WebService1Soap)(this)).CrisisStatusFeedback(inValue);
            return retVal.Body.CrisisStatusFeedbackResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1Tests.ServiceReference1.CrisisStatusFeedbackResponse> WebApplication1Tests.ServiceReference1.WebService1Soap.CrisisStatusFeedbackAsync(WebApplication1Tests.ServiceReference1.CrisisStatusFeedbackRequest request) {
            return base.Channel.CrisisStatusFeedbackAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1Tests.ServiceReference1.CrisisStatusFeedbackResponse> CrisisStatusFeedbackAsync(WebApplication1Tests.ServiceReference1.Request req) {
            WebApplication1Tests.ServiceReference1.CrisisStatusFeedbackRequest inValue = new WebApplication1Tests.ServiceReference1.CrisisStatusFeedbackRequest();
            inValue.Body = new WebApplication1Tests.ServiceReference1.CrisisStatusFeedbackRequestBody();
            inValue.Body.req = req;
            return ((WebApplication1Tests.ServiceReference1.WebService1Soap)(this)).CrisisStatusFeedbackAsync(inValue);
        }
    }
}
