using Microsoft.VisualStudio.TestTools.UnitTesting;
using SendPisResult.ISendPisResult.Impl.湖南省妇幼医院_广州邦弘;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using SendPisResult.Models;

namespace SendPisResult.ISendPisResult.Impl.湖南省妇幼医院_广州邦弘.Tests
{
    [TestClass()]
    public class SendResultImplTest 
    {
        [TestMethod()]
        public void SendResultTest()
        {
            //住院:201608928,bz,湖南省妇幼医院_广州邦弘
            //门诊:10152376,bz,湖南省妇幼医院_广州邦弘
            var args = "201702996,bz,湖南省妇幼医院_广州邦弘";
            var values = args.Split(',');
            var hospName = values[2]; //医院名称
            var pathoNo = values[0]; //病理号
            ISendPisResult sender = PisResultSenderFactory.GerResultSender(hospName);
            sender.SendResult(pathoNo);
        }

        [TestMethod()]
        public void ShowApplicationSelectorTest()
        {
            #region TestData
            var sxml = @"<PatientList>
<rows>
<CARDNUMBER>430423196808019104</CARDNUMBER>
<REQUISITIONID>B54537076</REQUISITIONID>
<PATIENTNAME>金少云</PATIENTNAME>
<PATIENTBIRTHDAY>1968/8/1 0:00:00</PATIENTBIRTHDAY>
<PATIENTSEX>女</PATIENTSEX>
<PATIENTAGE>48年7月</PATIENTAGE>
<PATIENTUNIT></PATIENTUNIT>
<PATIENTFROM>住院</PATIENTFROM>
<CLINICALNUM></CLINICALNUM>
<INHOSPITALNUM>00455238</INHOSPITALNUM>
<EXAMINETYPE>病理</EXAMINETYPE>
<EXAMINEPARTS>手术标本检查与诊断</EXAMINEPARTS>
<SENTBYDEPARTMENT>乳腺外科</SENTBYDEPARTMENT>
<SENTBYDOCTOR>林春华</SENTBYDOCTOR>
<FEE>96.00</FEE>
<ACUTELEVELDIAGNOSIS></ACUTELEVELDIAGNOSIS>
<CLINICALDIAGNOSIS>乳腺恶性肿瘤</CLINICALDIAGNOSIS>
<PATIENTTELEPHONE>15581631834</PATIENTTELEPHONE>
<BEDNUM>31</BEDNUM>
<PATIENTADDRESS>湖南省衡山县开云镇龙泉村杨家组5号</PATIENTADDRESS>
<DOCTORCHARGESTIME>2017/2/22 11:53:14</DOCTORCHARGESTIME>
<INPATIENT_ID>239093</INPATIENT_ID>
<BABY_ID>0</BABY_ID>
<QFBZ></QFBZ>
<exid>4781</exid>
</rows>
<rows>
<CARDNUMBER>430423196808019104</CARDNUMBER>
<REQUISITIONID>B54739169</REQUISITIONID>
<PATIENTNAME>金少云</PATIENTNAME>
<PATIENTBIRTHDAY>1968/8/1 0:00:00</PATIENTBIRTHDAY>
<PATIENTSEX>女</PATIENTSEX>
<PATIENTAGE>48年7月</PATIENTAGE>
<PATIENTUNIT></PATIENTUNIT>
<PATIENTFROM>住院</PATIENTFROM>
<CLINICALNUM></CLINICALNUM>
<INHOSPITALNUM>00455238</INHOSPITALNUM>
<EXAMINETYPE>病理</EXAMINETYPE>
<EXAMINEPARTS>手术标本检查与诊断</EXAMINEPARTS>
<SENTBYDEPARTMENT>乳腺外科</SENTBYDEPARTMENT>
<SENTBYDOCTOR>林春华</SENTBYDOCTOR>
<FEE>96.00</FEE>
<ACUTELEVELDIAGNOSIS></ACUTELEVELDIAGNOSIS>
<CLINICALDIAGNOSIS>乳腺恶性肿瘤</CLINICALDIAGNOSIS>
<PATIENTTELEPHONE>15581631834</PATIENTTELEPHONE>
<BEDNUM>31</BEDNUM>
<PATIENTADDRESS>湖南省衡山县开云镇龙泉村杨家组5号</PATIENTADDRESS>
<DOCTORCHARGESTIME>2017/3/2 10:50:45</DOCTORCHARGESTIME>
<INPATIENT_ID>239093</INPATIENT_ID>
<BABY_ID>0</BABY_ID>
<QFBZ></QFBZ>
<exid>4782</exid>
</rows>
<rows>
<CARDNUMBER>430423196808019104</CARDNUMBER>
<REQUISITIONID>B54511332</REQUISITIONID>
<PATIENTNAME>金少云</PATIENTNAME>
<PATIENTBIRTHDAY>1968/8/1 0:00:00</PATIENTBIRTHDAY>
<PATIENTSEX>女</PATIENTSEX>
<PATIENTAGE>48年7月</PATIENTAGE>
<PATIENTUNIT></PATIENTUNIT>
<PATIENTFROM>住院</PATIENTFROM>
<CLINICALNUM></CLINICALNUM>
<INHOSPITALNUM>00455238</INHOSPITALNUM>
<EXAMINETYPE>病理</EXAMINETYPE>
<EXAMINEPARTS>冰冻切片检查与诊断</EXAMINEPARTS>
<SENTBYDEPARTMENT>乳腺外科</SENTBYDEPARTMENT>
<SENTBYDOCTOR>林春华</SENTBYDOCTOR>
<FEE>160.00</FEE>
<ACUTELEVELDIAGNOSIS></ACUTELEVELDIAGNOSIS>
<CLINICALDIAGNOSIS>乳腺恶性肿瘤</CLINICALDIAGNOSIS>
<PATIENTTELEPHONE>15581631834</PATIENTTELEPHONE>
<BEDNUM>31</BEDNUM>
<PATIENTADDRESS>湖南省衡山县开云镇龙泉村杨家组5号</PATIENTADDRESS>
<DOCTORCHARGESTIME>2017/2/21 11:18:35</DOCTORCHARGESTIME>
<INPATIENT_ID>239093</INPATIENT_ID>
<BABY_ID>0</BABY_ID>
<QFBZ></QFBZ>
<exid>4783</exid>
</rows>
<rows>
<CARDNUMBER>430423196808019104</CARDNUMBER>
<REQUISITIONID>B54511333</REQUISITIONID>
<PATIENTNAME>金少云</PATIENTNAME>
<PATIENTBIRTHDAY>1968/8/1 0:00:00</PATIENTBIRTHDAY>
<PATIENTSEX>女</PATIENTSEX>
<PATIENTAGE>48年7月</PATIENTAGE>
<PATIENTUNIT></PATIENTUNIT>
<PATIENTFROM>住院</PATIENTFROM>
<CLINICALNUM></CLINICALNUM>
<INHOSPITALNUM>00455238</INHOSPITALNUM>
<EXAMINETYPE>病理</EXAMINETYPE>
<EXAMINEPARTS>病理体视学检查与图象分析</EXAMINEPARTS>
<SENTBYDEPARTMENT>乳腺外科</SENTBYDEPARTMENT>
<SENTBYDOCTOR>林春华</SENTBYDOCTOR>
<FEE>60.00</FEE>
<ACUTELEVELDIAGNOSIS></ACUTELEVELDIAGNOSIS>
<CLINICALDIAGNOSIS>乳腺恶性肿瘤</CLINICALDIAGNOSIS>
<PATIENTTELEPHONE>15581631834</PATIENTTELEPHONE>
<BEDNUM>31</BEDNUM>
<PATIENTADDRESS>湖南省衡山县开云镇龙泉村杨家组5号</PATIENTADDRESS>
<DOCTORCHARGESTIME>2017/2/21 11:18:35</DOCTORCHARGESTIME>
<INPATIENT_ID>239093</INPATIENT_ID>
<BABY_ID>0</BABY_ID>
<QFBZ></QFBZ>
<exid>4784</exid>
</rows>
<rows>
<CARDNUMBER>430423196808019104</CARDNUMBER>
<REQUISITIONID>B54537077</REQUISITIONID>
<PATIENTNAME>金少云</PATIENTNAME>
<PATIENTBIRTHDAY>1968/8/1 0:00:00</PATIENTBIRTHDAY>
<PATIENTSEX>女</PATIENTSEX>
<PATIENTAGE>48年7月</PATIENTAGE>
<PATIENTUNIT></PATIENTUNIT>
<PATIENTFROM>住院</PATIENTFROM>
<CLINICALNUM></CLINICALNUM>
<INHOSPITALNUM>00455238</INHOSPITALNUM>
<EXAMINETYPE>病理</EXAMINETYPE>
<EXAMINEPARTS>病理体视学检查与图象分析</EXAMINEPARTS>
<SENTBYDEPARTMENT>乳腺外科</SENTBYDEPARTMENT>
<SENTBYDOCTOR>林春华</SENTBYDOCTOR>
<FEE>60.00</FEE>
<ACUTELEVELDIAGNOSIS></ACUTELEVELDIAGNOSIS>
<CLINICALDIAGNOSIS>乳腺恶性肿瘤</CLINICALDIAGNOSIS>
<PATIENTTELEPHONE>15581631834</PATIENTTELEPHONE>
<BEDNUM>31</BEDNUM>
<PATIENTADDRESS>湖南省衡山县开云镇龙泉村杨家组5号</PATIENTADDRESS>
<DOCTORCHARGESTIME>2017/2/22 11:53:14</DOCTORCHARGESTIME>
<INPATIENT_ID>239093</INPATIENT_ID>
<BABY_ID>0</BABY_ID>
<QFBZ></QFBZ>
<exid>4785</exid>
</rows>
<rows>
<CARDNUMBER>430423196808019104</CARDNUMBER>
<REQUISITIONID>B54739170</REQUISITIONID>
<PATIENTNAME>金少云</PATIENTNAME>
<PATIENTBIRTHDAY>1968/8/1 0:00:00</PATIENTBIRTHDAY>
<PATIENTSEX>女</PATIENTSEX>
<PATIENTAGE>48年7月</PATIENTAGE>
<PATIENTUNIT></PATIENTUNIT>
<PATIENTFROM>住院</PATIENTFROM>
<CLINICALNUM></CLINICALNUM>
<INHOSPITALNUM>00455238</INHOSPITALNUM>
<EXAMINETYPE>病理</EXAMINETYPE>
<EXAMINEPARTS>病理体视学检查与图象分析</EXAMINEPARTS>
<SENTBYDEPARTMENT>乳腺外科</SENTBYDEPARTMENT>
<SENTBYDOCTOR>林春华</SENTBYDOCTOR>
<FEE>60.00</FEE>
<ACUTELEVELDIAGNOSIS></ACUTELEVELDIAGNOSIS>
<CLINICALDIAGNOSIS>乳腺恶性肿瘤</CLINICALDIAGNOSIS>
<PATIENTTELEPHONE>15581631834</PATIENTTELEPHONE>
<BEDNUM>31</BEDNUM>
<PATIENTADDRESS>湖南省衡山县开云镇龙泉村杨家组5号</PATIENTADDRESS>
<DOCTORCHARGESTIME>2017/3/2 10:50:45</DOCTORCHARGESTIME>
<INPATIENT_ID>239093</INPATIENT_ID>
<BABY_ID>0</BABY_ID>
<QFBZ></QFBZ>
<exid>4786</exid>
</rows>
<rows>
<CARDNUMBER>430423196808019104</CARDNUMBER>
<REQUISITIONID>B54511334</REQUISITIONID>
<PATIENTNAME>金少云</PATIENTNAME>
<PATIENTBIRTHDAY>1968/8/1 0:00:00</PATIENTBIRTHDAY>
<PATIENTSEX>女</PATIENTSEX>
<PATIENTAGE>48年7月</PATIENTAGE>
<PATIENTUNIT></PATIENTUNIT>
<PATIENTFROM>住院</PATIENTFROM>
<CLINICALNUM></CLINICALNUM>
<INHOSPITALNUM>00455238</INHOSPITALNUM>
<EXAMINETYPE>病理</EXAMINETYPE>
<EXAMINEPARTS>病理大体标本摄影</EXAMINEPARTS>
<SENTBYDEPARTMENT>乳腺外科</SENTBYDEPARTMENT>
<SENTBYDOCTOR>林春华</SENTBYDOCTOR>
<FEE>20.00</FEE>
<ACUTELEVELDIAGNOSIS></ACUTELEVELDIAGNOSIS>
<CLINICALDIAGNOSIS>乳腺恶性肿瘤</CLINICALDIAGNOSIS>
<PATIENTTELEPHONE>15581631834</PATIENTTELEPHONE>
<BEDNUM>31</BEDNUM>
<PATIENTADDRESS>湖南省衡山县开云镇龙泉村杨家组5号</PATIENTADDRESS>
<DOCTORCHARGESTIME>2017/2/21 11:18:35</DOCTORCHARGESTIME>
<INPATIENT_ID>239093</INPATIENT_ID>
<BABY_ID>0</BABY_ID>
<QFBZ></QFBZ>
<exid>4787</exid>
</rows>
<rows>
<CARDNUMBER>430423196808019104</CARDNUMBER>
<REQUISITIONID>B54537078</REQUISITIONID>
<PATIENTNAME>金少云</PATIENTNAME>
<PATIENTBIRTHDAY>1968/8/1 0:00:00</PATIENTBIRTHDAY>
<PATIENTSEX>女</PATIENTSEX>
<PATIENTAGE>48年7月</PATIENTAGE>
<PATIENTUNIT></PATIENTUNIT>
<PATIENTFROM>住院</PATIENTFROM>
<CLINICALNUM></CLINICALNUM>
<INHOSPITALNUM>00455238</INHOSPITALNUM>
<EXAMINETYPE>病理</EXAMINETYPE>
<EXAMINEPARTS>病理大体标本摄影</EXAMINEPARTS>
<SENTBYDEPARTMENT>乳腺外科</SENTBYDEPARTMENT>
<SENTBYDOCTOR>林春华</SENTBYDOCTOR>
<FEE>20.00</FEE>
<ACUTELEVELDIAGNOSIS></ACUTELEVELDIAGNOSIS>
<CLINICALDIAGNOSIS>乳腺恶性肿瘤</CLINICALDIAGNOSIS>
<PATIENTTELEPHONE>15581631834</PATIENTTELEPHONE>
<BEDNUM>31</BEDNUM>
<PATIENTADDRESS>湖南省衡山县开云镇龙泉村杨家组5号</PATIENTADDRESS>
<DOCTORCHARGESTIME>2017/2/22 11:53:14</DOCTORCHARGESTIME>
<INPATIENT_ID>239093</INPATIENT_ID>
<BABY_ID>0</BABY_ID>
<QFBZ></QFBZ>
<exid>4788</exid>
</rows>
<rows>
<CARDNUMBER>430423196808019104</CARDNUMBER>
<REQUISITIONID>B54739171</REQUISITIONID>
<PATIENTNAME>金少云</PATIENTNAME>
<PATIENTBIRTHDAY>1968/8/1 0:00:00</PATIENTBIRTHDAY>
<PATIENTSEX>女</PATIENTSEX>
<PATIENTAGE>48年7月</PATIENTAGE>
<PATIENTUNIT></PATIENTUNIT>
<PATIENTFROM>住院</PATIENTFROM>
<CLINICALNUM></CLINICALNUM>
<INHOSPITALNUM>00455238</INHOSPITALNUM>
<EXAMINETYPE>病理</EXAMINETYPE>
<EXAMINEPARTS>病理大体标本摄影</EXAMINEPARTS>
<SENTBYDEPARTMENT>乳腺外科</SENTBYDEPARTMENT>
<SENTBYDOCTOR>林春华</SENTBYDOCTOR>
<FEE>20.00</FEE>
<ACUTELEVELDIAGNOSIS></ACUTELEVELDIAGNOSIS>
<CLINICALDIAGNOSIS>乳腺恶性肿瘤</CLINICALDIAGNOSIS>
<PATIENTTELEPHONE>15581631834</PATIENTTELEPHONE>
<BEDNUM>31</BEDNUM>
<PATIENTADDRESS>湖南省衡山县开云镇龙泉村杨家组5号</PATIENTADDRESS>
<DOCTORCHARGESTIME>2017/3/2 10:50:45</DOCTORCHARGESTIME>
<INPATIENT_ID>239093</INPATIENT_ID>
<BABY_ID>0</BABY_ID>
<QFBZ></QFBZ>
<exid>4789</exid>
</rows>
<rows>
<CARDNUMBER>430423196808019104</CARDNUMBER>
<REQUISITIONID>B54537079</REQUISITIONID>
<PATIENTNAME>金少云</PATIENTNAME>
<PATIENTBIRTHDAY>1968/8/1 0:00:00</PATIENTBIRTHDAY>
<PATIENTSEX>女</PATIENTSEX>
<PATIENTAGE>48年7月</PATIENTAGE>
<PATIENTUNIT></PATIENTUNIT>
<PATIENTFROM>住院</PATIENTFROM>
<CLINICALNUM></CLINICALNUM>
<INHOSPITALNUM>00455238</INHOSPITALNUM>
<EXAMINETYPE>病理</EXAMINETYPE>
<EXAMINEPARTS>手术标本检查与诊断--每超过2个腊块</EXAMINEPARTS>
<SENTBYDEPARTMENT>乳腺外科</SENTBYDEPARTMENT>
<SENTBYDOCTOR>林春华</SENTBYDOCTOR>
<FEE>10.00</FEE>
<ACUTELEVELDIAGNOSIS></ACUTELEVELDIAGNOSIS>
<CLINICALDIAGNOSIS>乳腺恶性肿瘤</CLINICALDIAGNOSIS>
<PATIENTTELEPHONE>15581631834</PATIENTTELEPHONE>
<BEDNUM>31</BEDNUM>
<PATIENTADDRESS>湖南省衡山县开云镇龙泉村杨家组5号</PATIENTADDRESS>
<DOCTORCHARGESTIME>2017/2/22 11:53:14</DOCTORCHARGESTIME>
<INPATIENT_ID>239093</INPATIENT_ID>
<BABY_ID>0</BABY_ID>
<QFBZ></QFBZ>
<exid>4790</exid>
</rows>
<rows>
<CARDNUMBER>430423196808019104</CARDNUMBER>
<REQUISITIONID>B54739172</REQUISITIONID>
<PATIENTNAME>金少云</PATIENTNAME>
<PATIENTBIRTHDAY>1968/8/1 0:00:00</PATIENTBIRTHDAY>
<PATIENTSEX>女</PATIENTSEX>
<PATIENTAGE>48年7月</PATIENTAGE>
<PATIENTUNIT></PATIENTUNIT>
<PATIENTFROM>住院</PATIENTFROM>
<CLINICALNUM></CLINICALNUM>
<INHOSPITALNUM>00455238</INHOSPITALNUM>
<EXAMINETYPE>病理</EXAMINETYPE>
<EXAMINEPARTS>手术标本检查与诊断--每超过2个腊块</EXAMINEPARTS>
<SENTBYDEPARTMENT>乳腺外科</SENTBYDEPARTMENT>
<SENTBYDOCTOR>林春华</SENTBYDOCTOR>
<FEE>10.00</FEE>
<ACUTELEVELDIAGNOSIS></ACUTELEVELDIAGNOSIS>
<CLINICALDIAGNOSIS>乳腺恶性肿瘤</CLINICALDIAGNOSIS>
<PATIENTTELEPHONE>15581631834</PATIENTTELEPHONE>
<BEDNUM>31</BEDNUM>
<PATIENTADDRESS>湖南省衡山县开云镇龙泉村杨家组5号</PATIENTADDRESS>
<DOCTORCHARGESTIME>2017/3/2 10:50:45</DOCTORCHARGESTIME>
<INPATIENT_ID>239093</INPATIENT_ID>
<BABY_ID>0</BABY_ID>
<QFBZ></QFBZ>
<exid>4967</exid>
</rows>
<rows>
<CARDNUMBER>430423196808019104</CARDNUMBER>
<REQUISITIONID>B54593315</REQUISITIONID>
<PATIENTNAME>金少云</PATIENTNAME>
<PATIENTBIRTHDAY>1968/8/1 0:00:00</PATIENTBIRTHDAY>
<PATIENTSEX>女</PATIENTSEX>
<PATIENTAGE>48年7月</PATIENTAGE>
<PATIENTUNIT></PATIENTUNIT>
<PATIENTFROM>住院</PATIENTFROM>
<CLINICALNUM></CLINICALNUM>
<INHOSPITALNUM>00455238</INHOSPITALNUM>
<EXAMINETYPE>病理</EXAMINETYPE>
<EXAMINEPARTS>免疫组织化学染色诊断--全自动液盖膜单独温控法</EXAMINEPARTS>
<SENTBYDEPARTMENT>乳腺外科</SENTBYDEPARTMENT>
<SENTBYDOCTOR>林春华</SENTBYDOCTOR>
<FEE>150.00</FEE>
<ACUTELEVELDIAGNOSIS></ACUTELEVELDIAGNOSIS>
<CLINICALDIAGNOSIS>乳腺恶性肿瘤</CLINICALDIAGNOSIS>
<PATIENTTELEPHONE>15581631834</PATIENTTELEPHONE>
<BEDNUM>31</BEDNUM>
<PATIENTADDRESS>湖南省衡山县开云镇龙泉村杨家组5号</PATIENTADDRESS>
<DOCTORCHARGESTIME>2017/2/24 14:59:04</DOCTORCHARGESTIME>
<INPATIENT_ID>239093</INPATIENT_ID>
<BABY_ID>0</BABY_ID>
<QFBZ></QFBZ>
<exid>4792</exid>
</rows>
<rows>
<CARDNUMBER>430423196808019104</CARDNUMBER>
<REQUISITIONID>B54595343</REQUISITIONID>
<PATIENTNAME>金少云</PATIENTNAME>
<PATIENTBIRTHDAY>1968/8/1 0:00:00</PATIENTBIRTHDAY>
<PATIENTSEX>女</PATIENTSEX>
<PATIENTAGE>48年7月</PATIENTAGE>
<PATIENTUNIT></PATIENTUNIT>
<PATIENTFROM>住院</PATIENTFROM>
<CLINICALNUM></CLINICALNUM>
<INHOSPITALNUM>00455238</INHOSPITALNUM>
<EXAMINETYPE>病理</EXAMINETYPE>
<EXAMINEPARTS>免疫组织化学染色诊断--全自动液盖膜单独温控法</EXAMINEPARTS>
<SENTBYDEPARTMENT>乳腺外科</SENTBYDEPARTMENT>
<SENTBYDOCTOR>林春华</SENTBYDOCTOR>
<FEE>150.00</FEE>
<ACUTELEVELDIAGNOSIS></ACUTELEVELDIAGNOSIS>
<CLINICALDIAGNOSIS>乳腺恶性肿瘤</CLINICALDIAGNOSIS>
<PATIENTTELEPHONE>15581631834</PATIENTTELEPHONE>
<BEDNUM>31</BEDNUM>
<PATIENTADDRESS>湖南省衡山县开云镇龙泉村杨家组5号</PATIENTADDRESS>
<DOCTORCHARGESTIME>2017/2/24 15:48:41</DOCTORCHARGESTIME>
<INPATIENT_ID>239093</INPATIENT_ID>
<BABY_ID>0</BABY_ID>
<QFBZ></QFBZ>
<exid>4793</exid>
</rows>
<rows>
<CARDNUMBER>430423196808019104</CARDNUMBER>
<REQUISITIONID>B54844384</REQUISITIONID>
<PATIENTNAME>金少云</PATIENTNAME>
<PATIENTBIRTHDAY>1968/8/1 0:00:00</PATIENTBIRTHDAY>
<PATIENTSEX>女</PATIENTSEX>
<PATIENTAGE>48年7月</PATIENTAGE>
<PATIENTUNIT></PATIENTUNIT>
<PATIENTFROM>住院</PATIENTFROM>
<CLINICALNUM></CLINICALNUM>
<INHOSPITALNUM>00455238</INHOSPITALNUM>
<EXAMINETYPE>病理</EXAMINETYPE>
<EXAMINEPARTS>免疫组织化学染色诊断--全自动液盖膜单独温控法</EXAMINEPARTS>
<SENTBYDEPARTMENT>乳腺外科</SENTBYDEPARTMENT>
<SENTBYDOCTOR>林春华</SENTBYDOCTOR>
<FEE>150.00</FEE>
<ACUTELEVELDIAGNOSIS></ACUTELEVELDIAGNOSIS>
<CLINICALDIAGNOSIS>乳腺恶性肿瘤</CLINICALDIAGNOSIS>
<PATIENTTELEPHONE>15581631834</PATIENTTELEPHONE>
<BEDNUM>31</BEDNUM>
<PATIENTADDRESS>湖南省衡山县开云镇龙泉村杨家组5号</PATIENTADDRESS>
<DOCTORCHARGESTIME>2017/3/6 16:19:52</DOCTORCHARGESTIME>
<INPATIENT_ID>239093</INPATIENT_ID>
<BABY_ID>0</BABY_ID>
<QFBZ></QFBZ>
<exid>4794</exid>
</rows>
<rows>
<CARDNUMBER>430423196808019104</CARDNUMBER>
<REQUISITIONID>31318703</REQUISITIONID>
<PATIENTNAME>金少云</PATIENTNAME>
<PATIENTBIRTHDAY>1968/8/1 0:00:00</PATIENTBIRTHDAY>
<PATIENTSEX>女</PATIENTSEX>
<PATIENTAGE>48年7月</PATIENTAGE>
<PATIENTUNIT></PATIENTUNIT>
<PATIENTFROM>住院</PATIENTFROM>
<CLINICALNUM></CLINICALNUM>
<INHOSPITALNUM>00455238</INHOSPITALNUM>
<EXAMINETYPE>超声</EXAMINETYPE>
<EXAMINEPARTS>B超常规检查</EXAMINEPARTS>
<SENTBYDEPARTMENT>乳腺外科</SENTBYDEPARTMENT>
<SENTBYDOCTOR>李釜丞</SENTBYDOCTOR>
<FEE>40.00</FEE>
<ACUTELEVELDIAGNOSIS></ACUTELEVELDIAGNOSIS>
<CLINICALDIAGNOSIS>乳腺恶性肿瘤</CLINICALDIAGNOSIS>
<PATIENTTELEPHONE>15581631834</PATIENTTELEPHONE>
<BEDNUM>31</BEDNUM>
<PATIENTADDRESS>湖南省衡山县开云镇龙泉村杨家组5号</PATIENTADDRESS>
<DOCTORCHARGESTIME>2017/2/28 9:07:27</DOCTORCHARGESTIME>
<INPATIENT_ID>239093</INPATIENT_ID>
<BABY_ID>0</BABY_ID>
<QFBZ></QFBZ>
<exid>4819</exid>
</rows>
<rows>
<CARDNUMBER>430423196808019104</CARDNUMBER>
<REQUISITIONID>31187897</REQUISITIONID>
<PATIENTNAME>金少云</PATIENTNAME>
<PATIENTBIRTHDAY>1968/8/1 0:00:00</PATIENTBIRTHDAY>
<PATIENTSEX>女</PATIENTSEX>
<PATIENTAGE>48年7月</PATIENTAGE>
<PATIENTUNIT></PATIENTUNIT>
<PATIENTFROM>住院</PATIENTFROM>
<CLINICALNUM></CLINICALNUM>
<INHOSPITALNUM>00455238</INHOSPITALNUM>
<EXAMINETYPE>放射</EXAMINETYPE>
<EXAMINEPARTS>数字化摄影(DR)</EXAMINEPARTS>
<SENTBYDEPARTMENT>乳腺外科</SENTBYDEPARTMENT>
<SENTBYDOCTOR>李釜丞</SENTBYDOCTOR>
<FEE>20.00</FEE>
<ACUTELEVELDIAGNOSIS></ACUTELEVELDIAGNOSIS>
<CLINICALDIAGNOSIS>乳腺恶性肿瘤</CLINICALDIAGNOSIS>
<PATIENTTELEPHONE>15581631834</PATIENTTELEPHONE>
<BEDNUM>31</BEDNUM>
<PATIENTADDRESS>湖南省衡山县开云镇龙泉村杨家组5号</PATIENTADDRESS>
<DOCTORCHARGESTIME>2017/2/20 9:40:54</DOCTORCHARGESTIME>
<INPATIENT_ID>239093</INPATIENT_ID>
<BABY_ID>0</BABY_ID>
<QFBZ></QFBZ>
<exid>4820</exid>
</rows>
<rows>
<CARDNUMBER>430423196808019104</CARDNUMBER>
<REQUISITIONID>31187896</REQUISITIONID>
<PATIENTNAME>金少云</PATIENTNAME>
<PATIENTBIRTHDAY>1968/8/1 0:00:00</PATIENTBIRTHDAY>
<PATIENTSEX>女</PATIENTSEX>
<PATIENTAGE>48年7月</PATIENTAGE>
<PATIENTUNIT></PATIENTUNIT>
<PATIENTFROM>住院</PATIENTFROM>
<CLINICALNUM></CLINICALNUM>
<INHOSPITALNUM>00455238</INHOSPITALNUM>
<EXAMINETYPE>放射</EXAMINETYPE>
<EXAMINEPARTS>C型臂术中透视</EXAMINEPARTS>
<SENTBYDEPARTMENT>乳腺外科</SENTBYDEPARTMENT>
<SENTBYDOCTOR>李釜丞</SENTBYDOCTOR>
<FEE>80.00</FEE>
<ACUTELEVELDIAGNOSIS></ACUTELEVELDIAGNOSIS>
<CLINICALDIAGNOSIS>乳腺恶性肿瘤</CLINICALDIAGNOSIS>
<PATIENTTELEPHONE>15581631834</PATIENTTELEPHONE>
<BEDNUM>31</BEDNUM>
<PATIENTADDRESS>湖南省衡山县开云镇龙泉村杨家组5号</PATIENTADDRESS>
<DOCTORCHARGESTIME>2017/2/20 9:40:54</DOCTORCHARGESTIME>
<INPATIENT_ID>239093</INPATIENT_ID>
<BABY_ID>0</BABY_ID>
<QFBZ></QFBZ>
<exid>4821</exid>
</rows>
<rows>
<CARDNUMBER>430423196808019104</CARDNUMBER>
<REQUISITIONID>31187898</REQUISITIONID>
<PATIENTNAME>金少云</PATIENTNAME>
<PATIENTBIRTHDAY>1968/8/1 0:00:00</PATIENTBIRTHDAY>
<PATIENTSEX>女</PATIENTSEX>
<PATIENTAGE>48年7月</PATIENTAGE>
<PATIENTUNIT></PATIENTUNIT>
<PATIENTFROM>住院</PATIENTFROM>
<CLINICALNUM></CLINICALNUM>
<INHOSPITALNUM>00455238</INHOSPITALNUM>
<EXAMINETYPE>放射</EXAMINETYPE>
<EXAMINEPARTS>乳腺钼靶摄片 8×10吋--使用激光片</EXAMINEPARTS>
<SENTBYDEPARTMENT>乳腺外科</SENTBYDEPARTMENT>
<SENTBYDOCTOR>李釜丞</SENTBYDOCTOR>
<FEE>96.00</FEE>
<ACUTELEVELDIAGNOSIS></ACUTELEVELDIAGNOSIS>
<CLINICALDIAGNOSIS>乳腺恶性肿瘤</CLINICALDIAGNOSIS>
<PATIENTTELEPHONE>15581631834</PATIENTTELEPHONE>
<BEDNUM>31</BEDNUM>
<PATIENTADDRESS>湖南省衡山县开云镇龙泉村杨家组5号</PATIENTADDRESS>
<DOCTORCHARGESTIME>2017/2/20 9:40:54</DOCTORCHARGESTIME>
<INPATIENT_ID>239093</INPATIENT_ID>
<BABY_ID>0</BABY_ID>
<QFBZ></QFBZ>
<exid>4822</exid>
</rows>
</PatientList>";
            #endregion

            var dt = 湖南省妇幼医院_广州邦弘.GetDataSetByXml(sxml).Tables[0];
            ApplicationSelector selector = new ApplicationSelector();
            selector.DataTable = dt;
            selector.ShowDialog();
        }

        [TestMethod()]
        public void GetImageFileTest()
        {
            湖南省妇幼医院_广州邦弘 f = new 湖南省妇幼医院_广州邦弘();
            var p = f.GetImageFile(new T_JCXX());
        }

        [TestMethod()]
        public void OutCheckFeeTest()
        {
            湖南省妇幼医院_广州邦弘 f = new 湖南省妇幼医院_广州邦弘();
            var jcxx = new T_JCXX();
            jcxx.F_MZH = "1140345105";

            f.OutCheckFee(jcxx);
        }
    }
}